<a href="https://colab.research.google.com/github/KunChen-tw/DeepLearning/blob/main/deeplearning1013_Ch4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 使用 convolve2d 直接計算

In [ ]:
import numpy as np
from scipy.signal import convolve2d

A = np.array([[1, 2, 3, 2, 1],
              [0, 5, 1, 1, 6],
              [4, 0, 2, 2, 2],
              [1, 2, 1, 1, 3],
              [1, 1, 5, 2, 2]], dtype=int)

V = np.array([[1, 3, 1], [0, 3, 0], [1, 0, 2]], dtype=int)

print(convolve2d(A, V, mode='valid'))
print(convolve2d(A, V, mode='same')) # 將原來的A外面再加一圈 0
print(convolve2d(A, V, mode='full')) # 將原來的A外面再加二圈 0


[[26 17 20]
 [ 9 23 21]
 [25 23 22]]
[[ 8 22 18 16 22]
 [14 26 17 20 30]
 [22  9 23 21 18]
 [ 7 25 23 22 21]
 [ 5  6 20 11  8]]
[[ 1  5 10 13 10  5  1]
 [ 0  8 22 18 16 22  6]
 [ 5 14 26 17 20 30  4]
 [ 1 22  9 23 21 18 15]
 [ 5  7 25 23 22 21  6]
 [ 1  5  6 20 11  8  6]
 [ 1  1  7  4 12  4  4]]
