<a href="https://colab.research.google.com/github/KunChen-tw/DeepLearning/blob/main/deeplearning1013_Ch4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 使用 convolve2d 直接計算

In [1]:
import numpy as np
from scipy.signal import convolve2d

A = np.array([[1, 2, 3, 2, 1],
        [0, 5, 1, 1, 6],
        [4, 0, 2, 2, 2],
        [1, 2, 1, 1, 3],
        [1, 1, 5, 2, 2]], dtype=int)

V = np.array([[1, 3, 0], [0, 3, 0], [1, 0, 2]], dtype=int)

print(convolve2d(A, V, mode='valid'))
print(convolve2d(A, V, mode='same')) # 將原來的A外面再加一圈 0
print(convolve2d(A, V, mode='full')) # 將原來的A外面再加二圈 0


[[22 17 18]
 [ 8 21 20]
 [24 22 17]]
[[ 8 22 13 15 21]
 [14 22 17 18 28]
 [22  8 21 20 17]
 [ 7 24 22 17 19]
 [ 5  6 20 11  8]]
[[ 1  5  9 11  7  3  0]
 [ 0  8 22 13 15 21  0]
 [ 5 14 22 17 18 28  2]
 [ 1 22  8 21 20 17 12]
 [ 5  7 24 22 17 19  4]
 [ 1  5  6 20 11  8  6]
 [ 1  1  7  4 12  4  4]]
