<a href="https://colab.research.google.com/github/KunChen-tw/DeepLearning/blob/main/Practice_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 安裝 torchviz

In [ ]:
!pip install torchviz

  Preparing metadata (setup.py) ... done
  Created wheel for torchviz: filename=torchviz-0.0.2-py3-none-any.whl size=4132 sha256=4047adb273b6e490ddd0d7803cb07a880674dc0f9497da55e31fcc7ac31aa514
  Stored in directory: /root/.cache/pip/wheels/4c/97/88/a02973217949e0db0c9f4346d154085f4725f99c4f15a87094
Successfully built torchviz


# Practice 1-3
Let $x=[1,2,3]$，$y = x^4$，$z=2y$，$u = $mean$(z)$。Try to generate a computational graph about this relation

In [ ]:
import torch
x = torch.tensor([1,2,3], dtype=torch.float32, requires_grad=True)
y = x ** 4
z = 2*y
u = z.mean()
u.backward()

print(x)
print(y)
print(z)
print(u)

from torchviz import make_dot
dot = make_dot(u)
dot.view()

tensor([1., 2., 3.], requires_grad=True)
tensor([ 1., 16., 81.], grad_fn=<PowBackward0>)
tensor([  2.,  32., 162.], grad_fn=<MulBackward0>)
tensor(65.3333, grad_fn=<MeanBackward0>)


'Digraph.gv.pdf'