<a href="https://colab.research.google.com/github/KunChen-tw/DeepLearning/blob/main/Practice_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice 4-2

$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
1 & 4 & 1
\end{bmatrix}
$$

In [1]:
import torch
import torch.nn as nn

# Define a 2x2 input feature map
input_tensor = torch.tensor([[1, 2, 3],
               [4, 5, 6],
               [1, 4, 1]], dtype=torch.float32).unsqueeze(0).unsqueeze(0)

# Shape after unsqueeze: (1, 1, 2, 2) to fit PyTorch's expected (batch_size, channels, height, width)

# Define a transposed convolution layer with a 2x2 kernel, stride 2, and no bias
deconv = nn.ConvTranspose2d(
    in_channels=1,      # Number of input channels
    out_channels=1,     # Number of output channels
    kernel_size=2,      # Size of the convolutional kernel
    stride=2,           # Stride value to expand the output size
    bias=False          # Disable bias term
)

# Manually set the weight of the transposed convolution kernel to a simple pattern
with torch.no_grad():
    deconv.weight = nn.Parameter(torch.tensor([[[[1, 1],
                           [1, 0]]]], dtype=torch.float32))

# Perform forward propagation through the transposed convolution layer
output_tensor = deconv(input_tensor)

# Print input and output details
print("Original input feature map:")
print(input_tensor[0][0])

print("Kernel:")
print(deconv.weight[0][0])

print("\nOutput feature map after transposed convolution:")
print(output_tensor[0][0])


Original input feature map:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 4., 1.]])
Kernel:
tensor([[1., 1.],
        [1., 0.]], grad_fn=<SelectBackward0>)

Output feature map after transposed convolution:
tensor([[1., 1., 2., 2., 3., 3.],
        [1., 0., 2., 0., 3., 0.],
        [4., 4., 5., 5., 6., 6.],
        [4., 0., 5., 0., 6., 0.],
        [1., 1., 4., 4., 1., 1.],
        [1., 0., 4., 0., 1., 0.]], grad_fn=<SelectBackward0>)
